### ISSUE TITLE
Interessant

### ISSUE THREAD

**Issue by sylvielsstfr** [ycopin/spectrogrism#1]
Bonjour,

J'ai testé le code spectrogrism et les notebooks.
Je suis potentiellement très intéressée par ce code dans le cadre d'un télescope auxiliaire de LSST pour mesurer/monitorer l'atmosphère.

Je vous recontacterai bientôt.

Sylvie

**Comment by ycopin** [comment]
Vous serez peut-être alors également intéressée par 

http://adsabs.harvard.edu/abs/2013A%26A...549A...8B
http://snfactory.in2p3.fr/soft/atmosphericExtinction/

(il faudrait vraiment que je le transfert vers github/gitlab).

**Comment by sylvielsstfr** [comment]
Oui merci, je vais comparer le modèle atmosphericExtinction.py avec mes simulations de l'atmosphère avec LibRadTran.
Je veux bien récupérer ce code python sur github/gitlab. (J'ai pu le télécharger à partir du lien).

À bientôt.

Sylvie
